/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BusinessTrendChart: typeof import('./src/components/BusinessTrendChart.vue')['default']
    DashboardMap: typeof import('./src/components/DashboardMap.vue')['default']
    DashboardSymbol: typeof import('./src/components/DashboardSymbol.vue')['default']
    DomainProgressChart: typeof import('./src/components/DomainProgressChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    MetadataManagementPanel: typeof import('./src/components/MetadataManagementPanel.vue')['default']
    NewTaskDialog: typeof import('./src/components/NewTaskDialog.vue')['default']
    OrganizationSwitcher: typeof import('./src/components/OrganizationSwitcher.vue')['default']
    PermissionManagementPanel: typeof import('./src/components/PermissionManagementPanel.vue')['default']
    PrimaryHeader: typeof import('./src/components/PrimaryHeader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskRangeMap: typeof import('./src/components/TaskRangeMap.vue')['default']
    TaskRangeThumbnail: typeof import('./src/components/TaskRangeThumbnail.vue')['default']
    TaskSchedulePicker: typeof import('./src/components/TaskSchedulePicker.vue')['default']
    UserAccountMenu: typeof import('./src/components/UserAccountMenu.vue')['default']
  }
}
