/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    DashboardMap: typeof import('./src/components/DashboardMap.vue')['default']
    DashboardSymbol: typeof import('./src/components/DashboardSymbol.vue')['default']
    DomainProgressChart: typeof import('./src/components/DomainProgressChart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElTag: typeof import('element-plus/es')['ElTag']
    NewTaskDialog: typeof import('./src/components/NewTaskDialog.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TaskRangeMap: typeof import('./src/components/TaskRangeMap.vue')['default']
  }
}
