<script setup lang="ts">
import { workflowStatusLabel } from '@/api/task-workflow'
import { useBackendTaskData } from './use-backend-task'
import TaskRangeMap from '@/components/TaskRangeMap.vue'
import SpotDistributionMap from '@/workspace-components/spot-identification/SpotDistributionMap.vue'
const props = defineProps<{ taskId?: string; title?: string; nodeKey?: string }>()
const { detail, flow, geometry, abnormals, results, images, logs, loading, errors, activeSpotId, task, selectedNode, taskFields, statisticsFields, selectedSpot, text, handleLabel, imageryPeriod, load } = useBackendTaskData(props)
</script>

<template>
  <div class="backend-task-panel">
    <header class="panel-heading"><div><h2>{{ title || '任务工作台' }}</h2><p>{{ task?.name || (loading ? '正在读取任务…' : '请选择业务任务') }}</p></div><button :disabled="loading" @click="load">刷新</button></header>
    <p v-if="loading" role="status">正在加载后端数据…</p>
    <div v-for="message in errors" :key="message" class="error" role="alert">{{ message }}</div>
    <template v-if="task">
      <section class="card"><h3>任务统计</h3><dl class="fields"><div v-for="[label, value] in statisticsFields" :key="label"><dt>{{ label }}</dt><dd>{{ text(value) }}</dd></div></dl></section>
      <section class="card"><h3>任务信息</h3><dl class="fields"><div v-for="[label, value] in taskFields" :key="label"><dt>{{ label }}</dt><dd>{{ text(value) }}</dd></div></dl><p>{{ task.description || '暂无任务说明' }}</p><p>成果要求：{{ task.resultRequirements?.join('、') || '暂无数据' }}</p><img v-if="task.coverImageThumbnailUrl || task.coverImageUrl" class="cover" :src="task.coverImageThumbnailUrl || task.coverImageUrl" alt="任务封面" /></section>
      <div class="data-grid">
        <section class="card map-card"><h3>任务范围与异常图斑 <small>{{ detail?.abnormalCount ?? abnormals.length }} 个 · {{ detail?.abnormalArea ?? '—' }} ㎡</small></h3><div v-if="geometry.features.length || abnormals.length" class="map"><TaskRangeMap :geo-json="geometry" :abnormal-points="abnormals" :active-abnormal-id="activeSpotId" :fit-abnormal-points="true" /></div><p v-else>暂无可展示范围或图斑</p></section>
        <section class="card spots"><h3>异常图斑</h3><button v-for="spot in abnormals" :key="spot.id" class="spot" :class="{ selected: activeSpotId === spot.id }" @click="activeSpotId = spot.id"><b>{{ spot.title }}</b><span>{{ spot.spotNo || spot.id }} · {{ spot.abnormalTypeDesc }} · {{ spot.area ?? '—' }} ㎡</span><small>{{ handleLabel(spot.handleStatus) }} · {{ text(spot.foundTime) }}</small></button><p v-if="!abnormals.length">暂无异常图斑</p><div v-if="selectedSpot" class="spot-detail"><p>{{ selectedSpot.description || '暂无图斑说明' }}</p><p>异常等级：{{ selectedSpot.abnormalLevel }} · 坐标：{{ selectedSpot.longitude ?? '—' }}, {{ selectedSpot.latitude ?? '—' }}</p><img v-if="selectedSpot.imageUrl" :src="selectedSpot.imageUrl" alt="异常图斑影像" /></div></section>
      </div>
      <section class="card"><h3>参考影像与任务素材</h3><div class="imagery-list"><article v-for="image in task.comparisonImages || []" :key="image.id"><b>{{ image.label }}</b><small>{{ text(image.captureTime) }}</small><img v-if="image.imageUrl" :src="image.imageUrl" :alt="image.label" /><div v-if="image.mapService" class="reference-map"><SpotDistributionMap :spot="selectedSpot" :period="imageryPeriod(image)" /></div><a v-if="image.mapService" :href="image.mapService.serviceUrl" target="_blank" rel="noopener noreferrer">查看影像服务 · {{ image.mapService.type }}</a></article><article v-for="image in images" :key="image.id"><b>{{ image.fileName }}</b><small>{{ text(image.shootTime) }}</small><img v-if="image.thumbnailUrl || image.imageUrl" :src="image.thumbnailUrl || image.imageUrl" :alt="image.fileName" /><a v-if="image.originalUrl" :href="image.originalUrl" target="_blank" rel="noopener noreferrer">查看原始素材</a></article></div><p v-if="!task.comparisonImages?.length && !images.length">暂无参考影像或任务素材</p></section>
      <section class="card"><h3>工作流与节点办理记录</h3><p v-if="!flow && !errors.some(message => message.startsWith('工作流'))">该任务尚未启动工作流，暂无节点进度、办理表单或附件。</p><template v-if="flow"><p>{{ flow.flowName }} · {{ workflowStatusLabel(flow.status) }}</p><div class="timeline"><article v-for="node in flow.timeline" :key="node.id"><b>{{ node.nodeName }} · {{ workflowStatusLabel(node.status) }}</b><p>{{ node.assigneeName || '暂无处理人' }} · {{ node.deptName || '暂无部门' }} · 期限 {{ text(node.deadline) }}</p><small>提交时间 {{ text(node.submitTime) }}</small></article></div><template v-if="selectedNode"><h4>{{ selectedNode.nodeName }}填写内容</h4><pre v-if="selectedNode.resultData != null">{{ JSON.stringify(selectedNode.resultData, null, 2) }}</pre><p v-else>暂无填写内容</p><h4>节点附件</h4><p v-for="file in selectedNode.files || []" :key="file.id">{{ file.fileName }} · {{ file.fileSize ?? '—' }} 字节 · {{ text(file.createTime) }}</p><p v-if="!selectedNode.files?.length">暂无节点附件</p></template></template></section>
      <section class="card"><h3>成果材料</h3><article v-for="result in results" :key="result.id" class="result"><b>{{ result.resultType }} · {{ result.parseStatusDesc }}</b><p>{{ result.operator || '暂无采集人' }} · {{ text(result.collectTime) }} · {{ result.fileCount }} 个文件</p><p v-for="file in result.files" :key="file.id">{{ file.fileName }} · {{ file.fileSize ?? '—' }} 字节</p></article><p v-if="!results.length">暂无成果材料</p></section>
      <section class="card"><h3>操作记录</h3><article v-for="log in logs" :key="log.id" class="log"><time>{{ text(log.createTime) }}</time><b>{{ log.operateTypeDesc }}</b><span>{{ log.operatorName || '暂无操作人' }} · {{ log.operateDesc }}<details v-if="log.detailJson"><summary>变更明细</summary><pre>{{ log.detailJson }}</pre></details></span></article><p v-if="!logs.length && !loading && !errors.some(message => message.startsWith('操作记录'))">暂无可见操作记录</p></section>
    </template>
  </div>
</template>

<style scoped>
.backend-task-panel{height:100%;overflow:auto;padding:18px;background:#eef3f6;color:#29475a;box-sizing:border-box}.panel-heading{display:flex;justify-content:space-between;align-items:center;margin-bottom:14px}.panel-heading h2{margin:0;font-size:20px}.panel-heading p{margin:6px 0;color:#64788b}button{padding:8px 14px;border:1px solid #ccdce6;border-radius:4px;background:white;color:#245b7b;cursor:pointer}button:disabled{opacity:.5;cursor:wait}.card{padding:16px;margin-bottom:14px;border:1px solid #d5e0e8;border-radius:6px;background:white}.card h3{margin:0 0 14px;font-size:15px}.card h3 small{font-weight:normal;color:#64788b}.card p{font-size:13px;line-height:1.7;white-space:pre-wrap}.fields{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin:0}.fields div{display:grid;gap:5px}.fields dt{color:#728797;font-size:12px}.fields dd{margin:0;font-size:13px;overflow-wrap:anywhere}.data-grid{display:grid;grid-template-columns:2fr 1fr;gap:14px}.map{height:360px}.spots{max-height:410px;overflow:auto}.spot{display:grid;width:100%;gap:5px;text-align:left;margin-bottom:8px}.spot.selected{background:#eaf6fc;border-color:#178bb7}.spot span,.spot small{font-size:12px;color:#64788b}.cover,.spot-detail img{max-height:160px;max-width:100%}.imagery-list{display:flex;flex-wrap:wrap;gap:18px}.reference-map{width:280px;height:220px}.imagery-list article{display:grid;gap:8px;max-width:280px}.imagery-list img{max-width:100%;max-height:160px}.imagery-list small{color:#64788b}.imagery-list a{font-size:12px;color:#1684b0}.timeline{display:grid;gap:12px}.timeline article,.result{border-bottom:1px solid #edf2f5;padding:8px 0}.log{display:grid;grid-template-columns:165px 130px 1fr;gap:12px;padding:10px 0;border-bottom:1px solid #edf2f5;font-size:12px}.error{padding:10px;margin-bottom:10px;background:#fff0ed;color:#a83d35}pre{white-space:pre-wrap;overflow-wrap:anywhere;background:#f5f8fa;padding:12px;font-size:12px}@media(max-width:900px){.fields{grid-template-columns:repeat(2,minmax(0,1fr))}.data-grid{grid-template-columns:1fr}.log{grid-template-columns:1fr}}
</style>
