<script setup lang="ts">
import { computed } from 'vue'
import type { PortalTask, WorkspaceNodeConfig } from '@/types'
import { useBackendTaskData } from '@/workspace-components/shared/use-backend-task'
const props = defineProps<{ task?: PortalTask; sceneName?: string; node?: WorkspaceNodeConfig }>()
const source = computed(() => props.task?.id)
const { task: backendTask, abnormals, logs, loading, errors, taskFields, text, load } = useBackendTaskData({ get taskId() { return source.value } })
</script>
<template>
  <div class="dispatch-page">
    <aside class="panel spots"><div class="panel-title">关联图斑 <small>{{ abnormals.length }} 个</small></div><label v-for="spot in abnormals" :key="spot.id" class="spot-row"><i v-if="spot.imageUrl" :style="{ background: `url(${spot.imageUrl}) center / cover` }"></i><span><b>{{ spot.title }}</b><small>{{ spot.spotNo || spot.id }} · {{ spot.area ?? '—' }} ㎡</small></span><em>{{ spot.abnormalTypeDesc }}</em></label><div v-if="!abnormals.length" class="batch-tip">暂无关联图斑</div></aside>
    <section class="panel form-panel"><div class="panel-title">核查任务编制 <small>{{ backendTask?.name }}</small></div><div class="form-grid"><label v-for="[label, value] in taskFields" :key="label">{{ label }}<input :value="text(value)" readonly /></label><label class="wide">核查要求<textarea :value="backendTask?.description || '暂无数据'" readonly /></label><label class="wide">成果要求<textarea :value="backendTask?.resultRequirements?.join('、') || '暂无数据'" readonly /></label></div></section>
    <aside class="right-col"><section class="panel preview"><div class="panel-title">任务预览</div><dl><dt>任务标题</dt><dd>{{ backendTask?.name }}</dd><dt>接收对象</dt><dd>{{ backendTask?.deptName }} / {{ backendTask?.assigneeName || '暂无负责人' }}</dd><dt>期限</dt><dd>{{ text(backendTask?.planEndTime) }}</dd><dt>任务状态</dt><dd>{{ backendTask?.taskStatusDesc }}</dd><dt>图斑数量</dt><dd>{{ abnormals.length }} 个</dd></dl></section><section class="panel records"><div class="panel-title">任务操作留痕 <small>{{ logs.length }} 条</small></div><div v-for="log in logs" :key="log.id" class="record"><b>{{ log.operateTypeDesc }}</b><span>{{ log.operatorName || '暂无操作人' }} · {{ log.operateDesc }}</span><small>{{ text(log.createTime) }}</small><details v-if="log.detailJson"><summary>变更明细</summary><pre>{{ log.detailJson }}</pre></details></div></section></aside>
    <footer class="action-bar panel"><span role="status">{{ errors.join('；') || (loading ? '正在加载真实任务…' : '任务数据来自后端') }}</span><button :disabled="loading" @click="load">刷新任务</button></footer>
  </div>
</template>

<style scoped lang="scss">
.dispatch-page{height:100%;min-height:0;display:grid;grid-template-columns:270px 1fr 330px;grid-template-rows:1fr 54px;gap:8px;padding:8px;background:#e8eef3;color:#29475a}.panel{min-height:0;overflow:hidden;background:#fff;border:1px solid #d5e0e8;border-radius:6px;box-shadow:0 2px 8px #1c3b5210}.panel-title{height:36px;display:flex;align-items:center;justify-content:space-between;padding:0 11px;border-bottom:1px solid #e6eef3;color:#1f3d52;font-size:13px;font-weight:700}.panel-title small{color:#7a8f9e;font-weight:500}
.spots{overflow:auto}.spot-row{display:grid;grid-template-columns:18px 46px 1fr 20px;gap:7px;align-items:center;padding:10px;border-bottom:1px solid #edf2f5;cursor:pointer}.spot-row>i{width:46px;height:36px;border-radius:3px;background:linear-gradient(145deg,#426b45,#927d4e)}.spot-row b,.spot-row small{display:block}.spot-row b{font-size:12px}.spot-row small{margin-top:3px;color:#7a8f9e;font-size:9px}.spot-row em{color:#d44646;font-style:normal;font-size:10px}.batch-tip{margin:10px;padding:10px;color:#6e7d42;background:#f6f9e9;border-left:3px solid #9bb43b;font-size:10px;line-height:1.6}
.form-panel{overflow:auto}.form-grid{display:grid;grid-template-columns:1fr 1fr;gap:13px;padding:14px}.form-grid label{display:grid;gap:6px;color:#607788;font-size:11px}.form-grid .wide{grid-column:1/-1}.form-grid input,.form-grid select,.form-grid textarea{box-sizing:border-box;width:100%;padding:0 9px;border:1px solid #ccdce6;border-radius:4px;color:#29475a;background:#fbfdfe}.form-grid input,.form-grid select{height:34px}.form-grid textarea{height:82px;padding-top:8px;resize:vertical}.upload{position:relative}.upload input{position:absolute;opacity:0;pointer-events:none}.upload span{height:42px;display:grid;place-items:center;color:#1985b5;border:1px dashed #87bfd7;border-radius:4px;background:#f4fafc;cursor:pointer}.selected-summary{margin:0 14px 14px;padding:10px;background:#f5f8fa;font-size:10px}.selected-summary b{margin-right:10px}.selected-summary span{display:inline-block;margin:3px;padding:4px 7px;color:#177ca6;background:#e3f3fa;border-radius:3px}
.right-col{min-height:0;display:grid;grid-template-rows:auto 1fr;gap:8px}.preview dl{display:grid;grid-template-columns:82px 1fr;margin:0;padding:9px 12px}.preview dt,.preview dd{margin:0;padding:7px 0;border-bottom:1px solid #edf2f5;font-size:11px}.preview dt{color:#7a8f9e}.preview dd{text-align:right;font-weight:600}.preview p{margin:0 12px 12px;padding:9px;color:#6b7f8c;background:#f5f8fa;font-size:10px;line-height:1.6}.records{overflow:auto}.record{padding:10px 12px;border-bottom:1px solid #edf2f5}.record b,.record span,.record small{display:block;font-size:10px}.record b{color:#187caa}.record span{margin-top:4px}.record small{margin-top:3px;color:#8294a1}
.action-bar{grid-column:1/-1;display:flex;align-items:center;justify-content:flex-end;gap:8px;padding:8px 12px}.action-bar span{margin-right:auto;color:#66808f;font-size:11px}.action-bar button{height:34px;padding:0 16px;color:#426174;background:#fff;border:1px solid #c8d9e4;border-radius:4px;cursor:pointer}.action-bar button.primary{color:#fff;background:#168bd2;border-color:#168bd2}.action-bar button:disabled{opacity:.45;cursor:not-allowed}
@media (max-width:1180px){.dispatch-page{grid-template-columns:clamp(210px,22vw,250px) minmax(380px,1fr) clamp(230px,24vw,275px);gap:6px;padding:6px}.form-grid{gap:9px;padding:10px}}
</style>

<style scoped>
.spot-row{grid-template-columns:1fr auto}.spot-row>i{display:none}.record pre{white-space:pre-wrap;overflow-wrap:anywhere;font-size:10px}.record details{font-size:10px}
</style>
