<script setup lang="ts">
import { computed, ref } from 'vue'
import type { PortalTask, WorkspaceNodeConfig } from '@/types'
import { useBackendTaskData } from '@/workspace-components/shared/use-backend-task'
import { workflowStatusLabel } from '@/api/task-workflow'
import TaskRangeMap from '@/components/TaskRangeMap.vue'
import SpotDistributionMap from '@/workspace-components/spot-identification/SpotDistributionMap.vue'
const props = defineProps<{ task?: PortalTask; sceneName?: string; node?: WorkspaceNodeConfig }>()
const source = computed(() => props.task?.id)
const { task: backendTask, flow, geometry, abnormals, results, logs, loading, errors, activeSpotId, selectedSpot, selectedNode, text, imageryPeriod, load } = useBackendTaskData({ get taskId() { return source.value } })
const selectedImage = ref(0)
const image = computed(() => backendTask.value?.comparisonImages?.[selectedImage.value])
const files = computed(() => results.value.flatMap(result => result.files.map(file => ({ ...file, status: result.parseStatusDesc }))))
</script>
<template>
  <div class="review-page">
    <aside class="panel case-list"><div class="panel-title">关联任务图斑 <small>{{ abnormals.length }} 个</small></div><button v-for="spot in abnormals" :key="spot.id" class="case-row" :class="{ active: activeSpotId === spot.id }" @click="activeSpotId = spot.id"><i>斑</i><span><b>{{ spot.title }}</b><small>{{ spot.spotNo || spot.id }} · {{ spot.area ?? '—' }} ㎡</small><em>{{ spot.abnormalTypeDesc }} · {{ text(spot.foundTime) }}</em></span></button><div v-if="!abnormals.length" class="empty">暂无关联图斑</div></aside>
    <section class="center-col"><div class="panel compare-panel"><div class="panel-title">复核影像与任务范围 <small>{{ backendTask?.name }}</small></div><div class="compare-view"><SpotDistributionMap v-if="image?.mapService" :spot="selectedSpot" :period="imageryPeriod(image)" /><img v-else-if="image?.imageUrl" :src="image.imageUrl" :alt="image.label" /><TaskRangeMap v-else-if="geometry.features.length || abnormals.length" :geo-json="geometry" :abnormal-points="abnormals" :active-abnormal-id="activeSpotId" :fit-abnormal-points="true" /><p v-else class="empty">暂无影像或任务范围</p></div><div class="image-strip"><button v-for="(item, index) in backendTask?.comparisonImages || []" :key="item.id" :class="{ active: selectedImage === index }" @click="selectedImage = index">{{ item.label }}</button></div></div><div class="panel materials"><div class="panel-title">归档材料</div><table><thead><tr><th>材料名称</th><th>类型</th><th>大小</th><th>状态</th></tr></thead><tbody><tr v-for="file in files" :key="file.id"><td>{{ file.fileName }}</td><td>{{ file.fileExt || '—' }}</td><td>{{ file.fileSize ?? '—' }} 字节</td><td>{{ file.status }}</td></tr></tbody></table><p v-if="!files.length" class="empty">暂无成果材料</p></div></section>
    <aside class="right-col"><div class="panel result-panel"><div class="panel-title">复核结论</div><dl><dt>事项编号</dt><dd>{{ backendTask?.taskNo }}</dd><dt>负责人</dt><dd>{{ backendTask?.assigneeName || '暂无数据' }}</dd><dt>任务状态</dt><dd>{{ backendTask?.taskStatusDesc }}</dd></dl><label>节点办理内容<textarea :value="selectedNode?.resultData == null ? '暂无后端办理内容' : JSON.stringify(selectedNode.resultData, null, 2)" readonly /></label></div><div class="panel workflow"><div class="panel-title">历史流程</div><div v-for="item in flow?.timeline || []" :key="item.id" class="flow-row"><i></i><div><b>{{ item.nodeName }} · {{ workflowStatusLabel(item.status) }}</b><small>{{ text(item.submitTime || item.createTime) }} · {{ item.assigneeName || '暂无处理人' }}</small></div></div><p v-if="!flow" class="empty">暂无工作流节点记录</p></div><div class="panel logs"><div class="panel-title">操作日志 <small>{{ logs.length }} 条</small></div><div v-for="log in logs" :key="log.id" class="log-row"><time>{{ text(log.createTime) }}</time><span>{{ log.operatorName || '暂无操作人' }}</span><b>{{ log.operateDesc }}</b></div></div></aside>
    <footer class="action-bar panel"><span role="status">{{ errors.join('；') || (loading ? '正在加载真实任务…' : '任务数据来自后端') }}</span><button :disabled="loading" @click="load">刷新任务</button></footer>
  </div>
</template>

<style scoped lang="scss">
.review-page{height:100%;min-height:0;display:grid;grid-template-columns:280px 1fr 330px;grid-template-rows:1fr 54px;gap:8px;padding:8px;background:#e8eef3;color:#29475a}.panel{min-height:0;overflow:hidden;background:#fff;border:1px solid #d5e0e8;border-radius:6px;box-shadow:0 2px 8px #1c3b5210}.panel-title{height:36px;display:flex;align-items:center;justify-content:space-between;padding:0 11px;border-bottom:1px solid #e6eef3;color:#1f3d52;font-size:13px;font-weight:700}.panel-title small{color:#7a8f9e;font-weight:500}
.case-list{overflow:auto}.tabs{height:42px;display:grid;grid-template-columns:repeat(3,1fr);border-bottom:1px solid #dce7ed}.tabs button{border:0;background:#f4f8fa;color:#637b8b;font-size:10px;cursor:pointer}.tabs button.active{color:#1585b4;background:#fff;border-bottom:2px solid #1585b4}.tabs small{padding:1px 4px;background:#dfeaf0;border-radius:8px}.case-row{width:100%;display:flex;gap:9px;padding:12px 10px;border:0;border-bottom:1px solid #edf2f5;background:#fff;text-align:left;cursor:pointer}.case-row.active{background:#eaf6fc;border-left:3px solid #168db7}.case-row>i{width:34px;height:34px;display:grid;place-items:center;flex:none;color:#fff;background:#168db7;border-radius:4px;font-style:normal}.case-row b,.case-row small,.case-row em{display:block}.case-row b{font-size:11px}.case-row small{margin-top:4px;color:#708695;font-size:9px}.case-row em{margin-top:4px;color:#9a7b44;font-style:normal;font-size:9px}.empty{padding:50px 10px;color:#8999a4;text-align:center}
.center-col{min-height:0;display:grid;grid-template-rows:1fr auto;gap:8px}.compare-panel{display:flex;flex-direction:column}.compare-view{position:relative;flex:1;min-height:240px;margin:10px 10px 4px;overflow:hidden;background:linear-gradient(145deg,#856b43,#4e6d42)}.before,.after{position:absolute;inset:0;display:flex;align-items:flex-end;padding:10px;box-sizing:border-box;background:linear-gradient(#0001,#0008),repeating-linear-gradient(135deg,#795f3c 0 24px,#8f7448 24px 48px)}.after{right:auto;overflow:hidden;background:linear-gradient(#0001,#0008),repeating-linear-gradient(135deg,#32613d 0 24px,#47784b 24px 48px)}.before span,.after span{color:#fff;white-space:nowrap;font-size:11px}.compare-view>i{position:absolute;top:0;bottom:0;width:3px;background:#fff;box-shadow:0 0 8px #000}.compare-panel>input{margin:0 10px}.image-strip{display:flex;gap:6px;align-items:center;padding:6px 10px 10px}.image-strip button{padding:6px 8px;color:#587184;background:#f3f7f9;border:1px solid #d3e1e8}.image-strip button.active{color:#fff;background:#168db7}.image-strip p{flex:1;margin:0 0 0 8px;color:#6e8190;font-size:10px}
table{width:100%;border-collapse:collapse;font-size:10px}th,td{padding:7px 9px;border-bottom:1px solid #edf2f5;text-align:left}th{color:#668090;background:#f5f8fa}td em{color:#1a9a63;font-style:normal}td em.pending{color:#ca871a}td button{color:#1684b0;border:0;background:transparent;cursor:pointer}
.right-col{min-height:0;display:grid;grid-template-rows:auto 1fr auto;gap:8px}.result-panel dl{display:grid;grid-template-columns:78px 1fr;margin:0;padding:7px 11px}.result-panel dt,.result-panel dd{margin:0;padding:6px 0;border-bottom:1px solid #edf2f5;font-size:10px}.result-panel dt{color:#7c8e9a}.result-panel dd{text-align:right;font-weight:600}.result-panel select{height:25px;border:1px solid #ccdce6}.result-panel label{display:grid;gap:5px;padding:0 11px 11px;color:#708592;font-size:10px}.result-panel textarea{height:64px;padding:7px;border:1px solid #ccdce6;resize:none}.workflow{overflow:auto}.flow-row{display:grid;grid-template-columns:12px 1fr;gap:7px;margin-left:15px;padding:8px 10px;border-left:1px solid #cddde7}.flow-row i{width:7px;height:7px;margin-left:-14px;border-radius:50%;background:#17a7bd}.flow-row b,.flow-row small{display:block;font-size:10px}.flow-row small{margin-top:3px;color:#8496a3}.log-row{display:grid;grid-template-columns:58px 42px 1fr;gap:6px;padding:7px 10px;border-bottom:1px solid #edf2f5;font-size:9px}.log-row time,.log-row span{color:#80939f}.log-row b{font-weight:500}
.action-bar{grid-column:1/-1;display:flex;align-items:center;justify-content:flex-end;gap:8px;padding:8px 12px}.action-bar span{margin-right:auto;color:#66808f;font-size:11px}.action-bar button{height:34px;padding:0 16px;color:#426174;background:#fff;border:1px solid #c8d9e4;border-radius:4px;cursor:pointer}.action-bar button.primary{color:#fff;background:#168bd2;border-color:#168bd2}
</style>

<style scoped>
.compare-view{background:#eef3f6}.compare-view>img{height:100%;width:100%;object-fit:contain}.materials,.logs{max-height:220px;overflow:auto}.log-row{grid-template-columns:110px 65px 1fr}.empty{padding:14px 10px}.image-strip{flex-wrap:wrap}
</style>
