import type { SceneWorkspaceConfig } from '@/types'

export const forestryConfig: SceneWorkspaceConfig = {
  sceneId: 'forestry-enforcement',
  name: '林业执法监管',
  modules: [
    { key: 'governance', name: '林业监管任务处置流程' },
  ],
  nodes: [
    // 两级审签顺序来自效果图需求，海陵区实际岗位/审批顺序应由业务管理员配置确认。
    {
      key: 'task-detail',
      name: '任务详情',
      shortName: '任务详情',
      order: 1,
      module: 'governance',
      component: 'TaskDetail',
      description: '查看任务图斑、区域范围与识别结论',
    },
    {
      key: 'director-review',
      name: '分管局长审核',
      shortName: '分管局长审核',
      order: 2,
      module: 'governance',
      component: 'ForestryApproval',
      description: '审阅疑似图斑与核查建议，选择下一审核岗位（示意，可配置）',
    },
    {
      key: 'section-review',
      name: '分管科长审核',
      shortName: '分管科长审核',
      order: 3,
      module: 'governance',
      component: 'ForestryApproval',
      description: '复核图斑材料及交办范围，选定任务派发经办人（示意，可配置）',
    },
    {
      key: 'task-dispatch',
      name: '核查任务派发',
      shortName: '任务派发',
      order: 4,
      module: 'governance',
      component: 'TaskDispatch',
      description: '选择属地核查人员并确认下发核查任务',
    },
    {
      key: 'field-verification',
      name: '实地核查',
      shortName: '实地核查',
      order: 5,
      module: 'governance',
      component: 'FieldVerification',
      description: '属地现场核实、拍照举证并反馈核查结论',
    },
    {
      key: 'rectification-tracking',
      name: '整改跟踪',
      shortName: '整改跟踪',
      order: 6,
      module: 'governance',
      component: 'RectificationTracking',
      description: '跟踪问题整改、期限与现场反馈',
    },
    {
      key: 'review-archive',
      name: '复核归档',
      shortName: '复核归档',
      order: 7,
      module: 'governance',
      component: 'ReviewArchive',
      description: '核验整改成果并形成案件档案',
    },
  ],
}
